# Generated by Django 3.2.9 on 2021-11-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0003_auto_20211111_0629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
